"""Remove activity_type from ExtraCurricular

Revision ID: 035a229deb3a
Revises: 2e75ec9ceb42
Create Date: 2025-06-09 10:54:09.715855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035a229deb3a'
down_revision = '2e75ec9ceb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_curricular', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_column('activity_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_curricular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###
