"""Create extracurricular table

Revision ID: ab6cf0d328eb
Revises: 035a229deb3a
Create Date: 2025-06-10 11:45:15.152992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6cf0d328eb'
down_revision = '035a229deb3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracurricular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('category', sa.String(length=140), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracurricular', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracurricular_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('extra_curricular', schema=None) as batch_op:
        batch_op.drop_index('ix_extra_curricular_timestamp')

    op.drop_table('extra_curricular')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extra_curricular',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extra_curricular', schema=None) as batch_op:
        batch_op.create_index('ix_extra_curricular_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('extracurricular', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracurricular_timestamp'))

    op.drop_table('extracurricular')
    # ### end Alembic commands ###
